In [ ]:
import pandas as pd

lab = pd.read_csv("ALL_DATA/lab.csv")
lab.head()

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
0,437880563,1754323,-647,3,Hct,38.30,38.3,%,%,-631
1,437880572,1754323,-647,3,platelets x 1000,181.00,181,K/mcL,k/mm cu,-631
2,437880560,1754323,-647,3,RBC,4.86,4.86,M/mcL,m/mm cu,-631
3,437880570,1754323,-647,3,-monos,8.70,8.7,%,%,-631
4,437880571,1754323,-647,3,MCHC,30.40,30.4,g/dL,%,-631

In [ ]:
lab = lab[['patientunitstayid', 'labresultoffset', 'labname', 'labresult']]
lab.head()

   patientunitstayid  labresultoffset           labname  labresult
0            1754323             -647               Hct      38.30
1            1754323             -647  platelets x 1000     181.00
2            1754323             -647               RBC       4.86
3            1754323             -647            -monos       8.70
4            1754323             -647              MCHC      30.40

In [ ]:
lab_pivot = lab.pivot_table('labresult', ['patientunitstayid', 'labresultoffset'], 'labname')

In [ ]:
lab_pivot.head(20)

labname                            -bands  -basos  -eos  -lymphs  -monos  \
patientunitstayid labresultoffset
141765            -169                NaN     0.0   0.0     10.0     4.0
                   81                 NaN     NaN   NaN      NaN     NaN
                   646                NaN     0.0   1.0     19.0    10.0
                   775                NaN     NaN   NaN      NaN     NaN
                   934                NaN     NaN   NaN      NaN     NaN
                   2086               NaN     NaN   NaN      NaN     NaN
143870            -190                NaN     NaN   NaN      NaN     NaN
                  -137                NaN     NaN   NaN      NaN     NaN
                  -61                 NaN     NaN   NaN      NaN     NaN
                   23                 NaN     NaN   NaN      NaN     NaN
                   791                NaN     0.0   0.0      8.0     4.0
144815            -195                NaN     0.0   0.0     16.0     6.0
                  -132                NaN     NaN   NaN      NaN     NaN
                   523                NaN     1.0   1.0     24.0     8.0
145427            -373                1.0     NaN   NaN      5.0     7.0
                  -359                NaN     NaN   NaN      NaN     NaN
                  -278                NaN     NaN   NaN      NaN     NaN
                   248                NaN     NaN   NaN      NaN     NaN
                   571                NaN     0.0   0.0      8.0     8.0
                   2048               NaN     0.0   1.0     35.0    11.0

labname                            -polys  24 h urine protein  \
patientunitstayid labresultoffset
141765            -169               86.0                 NaN
                   81                 NaN                 NaN
                   646               70.0                 NaN
                   775                NaN                 NaN
                   934                NaN                 NaN
                   2086               NaN                 NaN
143870            -190                NaN                 NaN
                  -137                NaN                 NaN
                  -61                 NaN                 NaN
                   23                 NaN                 NaN
                   791               88.0                 NaN
144815            -195               78.0                 NaN
                  -132                NaN                 NaN
                   523               66.0                 NaN
145427            -373               83.0                 NaN
                  -359                NaN                 NaN
                  -278                NaN                 NaN
                   248                NaN                 NaN
                   571               84.0                 NaN
                   2048              53.0                 NaN

labname                            24 h urine urea nitrogen  ALT (SGPT)  \
patientunitstayid labresultoffset
141765            -169                                  NaN        29.0
                   81                                   NaN         NaN
                   646                                  NaN         NaN
                   775                                  NaN         NaN
                   934                                  NaN         NaN
                   2086                                 NaN         NaN
143870            -190                                  NaN         NaN
                  -137                                  NaN         NaN
                  -61                                   NaN         NaN
                   23                                   NaN         NaN
                   791                                  NaN         NaN
144815            -195                                  NaN        51.0
                  -132                                  NaN         NaN
                   523                                  NaN        42.0
145427            -373                                  NaN        29.0
                  -359                                  NaN         NaN
                  -278                                  NaN         NaN
                   248                                  NaN         NaN
                   571                                  NaN         NaN
                   2048                                 NaN         NaN

labname                            ANF/ANA  ...  total protein  transferrin  \
patientunitstayid labresultoffset           ...
141765            -169                 NaN  ...            7.4          NaN
                   81                  NaN  ...            NaN          NaN
                   646                 NaN  ...            NaN          NaN
                   775                 NaN  ...            NaN          NaN
                   934                 NaN  ...            NaN          NaN
                   2086                NaN  ...            NaN          NaN
143870            -190                 NaN  ...            NaN          NaN
                  -137                 NaN  ...            NaN          NaN
                  -61                  NaN  ...            NaN          NaN
                   23                  NaN  ...            NaN          NaN
                   791                 NaN  ...            NaN          NaN
144815            -195                 NaN  ...            8.2          NaN
                  -132                 NaN  ...            NaN          NaN
                   523                 NaN  ...            7.0          NaN
145427            -373                 NaN  ...            6.8          NaN
                  -359                 NaN  ...            NaN          NaN
                  -278                 NaN  ...            NaN          NaN
                   248                 NaN  ...            NaN          NaN
                   571                 NaN  ...            NaN          NaN
                   2048                NaN  ...            NaN          NaN

labname                            triglycerides  troponin - I  troponin - T  \
patientunitstayid labresultoffset
141765            -169                       NaN          0.02           NaN
                   81                        NaN          0.02           NaN
                   646                       NaN           NaN           NaN
                   775                       NaN           NaN           NaN
                   934                       NaN           NaN           NaN
                   2086                      NaN           NaN           NaN
143870            -190                       NaN           NaN           NaN
                  -137                       NaN           NaN           NaN
                  -61                        NaN           NaN           NaN
                   23                        NaN           NaN           NaN
                   791                       NaN           NaN           NaN
144815            -195                       NaN           NaN           NaN
                  -132                       NaN           NaN           NaN
                   523                       NaN           NaN           NaN
145427            -373                       NaN           NaN           NaN
                  -359                       NaN           NaN           NaN
                  -278                       NaN           NaN           NaN
                   248                       NaN           NaN           NaN
                   571                       NaN           NaN           NaN
                   2048                      NaN           NaN           NaN

labname                            uric acid  urinary creatinine  \
patientunitstayid labresultoffset
141765            -169                   NaN                 NaN
                   81                    NaN                 NaN
                   646                   NaN                 NaN
                   775                   NaN                 NaN
                   934                   NaN                 NaN
                   2086                  NaN                 NaN
143870            -190                   NaN                 NaN
                  -137                   NaN                 NaN
                  -61                    NaN                 NaN
                   23                    NaN                 NaN
                   791                   NaN                 NaN
144815            -195                   NaN                 NaN
                  -132                   NaN                 NaN
                   523                   NaN                 NaN
145427            -373                   NaN                 NaN
                  -359                   NaN                 NaN
                  -278                   NaN                 NaN
                   248                   NaN                 NaN
                   571                   NaN                 NaN
                   2048                  NaN                 NaN

labname                            urinary osmolality  urinary sodium  \
patientunitstayid labresultoffset
141765            -169                            NaN             NaN
                   81                             NaN             NaN
                   646                            NaN             NaN
                   775                            NaN             NaN
                   934                            NaN             NaN
                   2086                           NaN             NaN
143870            -190                            NaN             NaN
                  -137                            NaN             NaN
                  -61                             NaN             NaN
                   23                             NaN             NaN
                   791                            NaN             NaN
144815            -195                            NaN             NaN
                  -132                            NaN             NaN
                   523                            NaN             NaN
145427            -373                            NaN             NaN
                  -359                            NaN             NaN
                  -278                            NaN             NaN
                   248                            NaN             NaN
                   571                            NaN             NaN
                   2048                           NaN             NaN

labname                            urinary specific gravity
patientunitstayid labresultoffset
141765            -169                                  NaN
                   81                                   NaN
                   646                                  NaN
                   775                                  NaN
                   934                                1.010
                   2086                                 NaN
143870            -190                                  NaN
                  -137                                  NaN
                  -61                                   NaN
                   23                                   NaN
                   791                                  NaN
144815            -195                                  NaN
                  -132                                  NaN
                   523                                  NaN
145427            -373                                  NaN
                  -359                                  NaN
                  -278                                1.015
                   248                                  NaN
                   571                                  NaN
                   2048                                 NaN

[20 rows x 144 columns]

In [ ]:
lab_pivot = lab_pivot[["albumin", "BUN", "bicarbonate", "creatinine", "FiO2", "glucose", "HCO3", "Hct", "paO2", "pH", "potassium", "Respiratory Rate", "sodium", "Temperature", "total bilirubin", "WBC x 1000"]]
lab_pivot.head(20)

labname                            albumin   BUN  bicarbonate  creatinine  \
patientunitstayid labresultoffset
141765            -169                 3.7  35.0         23.0        1.32
                   81                  NaN   NaN          NaN         NaN
                   646                 NaN  28.0         21.0        1.04
                   775                 NaN   NaN          NaN         NaN
                   934                 NaN   NaN          NaN         NaN
                   2086                NaN  16.0         26.0        0.85
143870            -190                 NaN   NaN          NaN         NaN
                  -137                 NaN   NaN          NaN         NaN
                  -61                  NaN   NaN          NaN         NaN
                   23                  NaN  13.0         25.0        0.89
                   791                 NaN  14.0         22.0        1.14
144815            -195                 4.2   6.0         24.0        0.75
                  -132                 NaN   NaN          NaN         NaN
                   523                 3.6   6.0         26.0        0.63
145427            -373                 3.7  19.0         29.0        1.12
                  -359                 NaN   NaN          NaN         NaN
                  -278                 NaN   NaN          NaN         NaN
                   248                 NaN   NaN          NaN         NaN
                   571                 NaN  14.0         27.0        1.05
                   2048                NaN   NaN          NaN         NaN

labname                            FiO2  glucose  HCO3   Hct   paO2    pH  \
patientunitstayid labresultoffset
141765            -169              NaN     91.0   NaN  37.5    NaN   NaN
                   81               NaN      NaN   NaN   NaN    NaN   NaN
                   646              NaN     61.0   NaN  37.8    NaN   NaN
                   775              NaN      NaN   NaN   NaN    NaN   NaN
                   934              NaN      NaN   NaN   NaN    NaN   NaN
                   2086             NaN     79.0   NaN   NaN    NaN   NaN
143870            -190             61.0      NaN  22.0   NaN   98.0  7.41
                  -137             49.0      NaN  23.0   NaN  219.0  7.39
                  -61               NaN      NaN   NaN   NaN    NaN   NaN
                   23               NaN    123.0   NaN   NaN    NaN   NaN
                   791              NaN    140.0   NaN  34.1    NaN   NaN
144815            -195              NaN     99.0   NaN  37.5    NaN   NaN
                  -132             21.0      NaN  21.0   NaN   71.0  7.40
                   523              NaN     82.0   NaN  36.6    NaN   NaN
145427            -373              NaN    118.0   NaN  44.2    NaN   NaN
                  -359              NaN      NaN   NaN   NaN    NaN   NaN
                  -278              NaN      NaN   NaN   NaN    NaN   NaN
                   248              NaN      NaN   NaN   NaN    NaN   NaN
                   571              NaN    139.0   NaN  40.4    NaN   NaN
                   2048             NaN      NaN   NaN  37.7    NaN   NaN

labname                            potassium  Respiratory Rate  sodium  \
patientunitstayid labresultoffset
141765            -169                   4.4               NaN   138.0
                   81                    NaN               NaN     NaN
                   646                   4.1               NaN   139.0
                   775                   NaN               NaN     NaN
                   934                   NaN               NaN     NaN
                   2086                  3.7               NaN   142.0
143870            -190                   NaN               NaN     NaN
                  -137                   NaN               NaN     NaN
                  -61                    NaN               NaN     NaN
                   23                    4.4               NaN   139.0
                   791                   4.4               NaN   133.0
144815            -195                   3.8               NaN   141.0
                  -132                   NaN               NaN     NaN
                   523                   3.7               NaN   141.0
145427            -373                   4.2               NaN   138.0
                  -359                   NaN               NaN     NaN
                  -278                   NaN               NaN     NaN
                   248                   NaN               NaN     NaN
                   571                   4.5               NaN   141.0
                   2048                  NaN               NaN     NaN

labname                            Temperature  total bilirubin  WBC x 1000
patientunitstayid labresultoffset
141765            -169                     NaN              0.8        11.1
                   81                      NaN              NaN         NaN
                   646                     NaN              NaN        10.2
                   775                     NaN              NaN         NaN
                   934                     NaN              NaN         NaN
                   2086                    NaN              NaN         NaN
143870            -190                     NaN              NaN         NaN
                  -137                     NaN              NaN         NaN
                  -61                      NaN              NaN         NaN
                   23                      NaN              NaN         NaN
                   791                     NaN              NaN        11.7
144815            -195                     NaN              0.5        10.5
                  -132                     NaN              NaN         NaN
                   523                     NaN              0.5         7.9
145427            -373                     NaN              0.8        19.0
                  -359                     NaN              NaN         NaN
                  -278                     NaN              NaN         NaN
                   248                     NaN              NaN         NaN
                   571                     NaN              NaN        21.1
                   2048                    NaN              NaN        14.2

In [ ]:
lab_pivot = lab_pivot.query('labresultoffset > 0')
lab_pivot.head()

labname                            albumin   BUN  bicarbonate  creatinine  \
patientunitstayid labresultoffset
141765            81                   NaN   NaN          NaN         NaN
                  646                  NaN  28.0         21.0        1.04
                  775                  NaN   NaN          NaN         NaN
                  934                  NaN   NaN          NaN         NaN
                  2086                 NaN  16.0         26.0        0.85

labname                            FiO2  glucose  HCO3   Hct  paO2  pH  \
patientunitstayid labresultoffset
141765            81                NaN      NaN   NaN   NaN   NaN NaN
                  646               NaN     61.0   NaN  37.8   NaN NaN
                  775               NaN      NaN   NaN   NaN   NaN NaN
                  934               NaN      NaN   NaN   NaN   NaN NaN
                  2086              NaN     79.0   NaN   NaN   NaN NaN

labname                            potassium  Respiratory Rate  sodium  \
patientunitstayid labresultoffset
141765            81                     NaN               NaN     NaN
                  646                    4.1               NaN   139.0
                  775                    NaN               NaN     NaN
                  934                    NaN               NaN     NaN
                  2086                   3.7               NaN   142.0

labname                            Temperature  total bilirubin  WBC x 1000
patientunitstayid labresultoffset
141765            81                       NaN              NaN         NaN
                  646                      NaN              NaN        10.2
                  775                      NaN              NaN         NaN
                  934                      NaN              NaN         NaN
                  2086                     NaN              NaN         NaN

In [ ]:
lab_pivot

labname                            albumin   BUN  bicarbonate  creatinine  \
patientunitstayid labresultoffset
141765            81                   NaN   NaN          NaN         NaN
                  646                  NaN  28.0         21.0        1.04
                  775                  NaN   NaN          NaN         NaN
                  934                  NaN   NaN          NaN         NaN
                  2086                 NaN  16.0         26.0        0.85
...                                    ...   ...          ...         ...
3352333           2296                 NaN   NaN          NaN         NaN
                  1933                 NaN   NaN          NaN         NaN
3353113           623                  3.6   6.0         23.0        0.57
                  3739                 NaN   NaN          NaN         NaN
                  1205                 NaN   NaN          NaN         NaN

labname                            FiO2  glucose  HCO3   Hct  paO2  pH  \
patientunitstayid labresultoffset
141765            81                NaN      NaN   NaN   NaN   NaN NaN
                  646               NaN     61.0   NaN  37.8   NaN NaN
                  775               NaN      NaN   NaN   NaN   NaN NaN
                  934               NaN      NaN   NaN   NaN   NaN NaN
                  2086              NaN     79.0   NaN   NaN   NaN NaN
...                                 ...      ...   ...   ...   ...  ..
3352333           2296              NaN      NaN   NaN   NaN   NaN NaN
                  1933              NaN      NaN   NaN   NaN   NaN NaN
3353113           623               NaN     82.0   NaN   NaN   NaN NaN
                  3739              NaN      NaN   NaN   NaN   NaN NaN
                  1205              NaN      NaN   NaN   NaN   NaN NaN

labname                            potassium  Respiratory Rate  sodium  \
patientunitstayid labresultoffset
141765            81                     NaN               NaN     NaN
                  646                    4.1               NaN   139.0
                  775                    NaN               NaN     NaN
                  934                    NaN               NaN     NaN
                  2086                   3.7               NaN   142.0
...                                      ...               ...     ...
3352333           2296                   NaN               NaN     NaN
                  1933                   NaN               NaN     NaN
3353113           623                    3.1               NaN   137.0
                  3739                   NaN               NaN     NaN
                  1205                   3.6               NaN     NaN

labname                            Temperature  total bilirubin  WBC x 1000
patientunitstayid labresultoffset
141765            81                       NaN              NaN         NaN
                  646                      NaN              NaN        10.2
                  775                      NaN              NaN         NaN
                  934                      NaN              NaN         NaN
                  2086                     NaN              NaN         NaN
...                                        ...              ...         ...
3352333           2296                     NaN              NaN         NaN
                  1933                     NaN              NaN         NaN
3353113           623                      NaN              1.3         NaN
                  3739                     NaN              NaN         NaN
                  1205                     NaN              NaN         NaN

[50054 rows x 16 columns]

In [ ]:
lab_pivot = lab_pivot.reset_index(level=[0,1])

In [ ]:
lab_pivot = lab_pivot.drop(['labresultoffset'], axis=1)

In [ ]:
lab_pivot = lab_pivot.drop_duplicates(subset=['patientunitstayid'], keep='last')

In [ ]:
lab_pivot["fiO2/paO2 ratio"] = lab_pivot.FiO2/lab_pivot.paO2

In [ ]:
lab_pivot

labname,patientunitstayid,albumin,BUN,bicarbonate,creatinine,FiO2,glucose,HCO3,Hct,paO2,pH,potassium,Respiratory Rate,sodium,Temperature,total bilirubin,WBC x 1000,fiO2/paO2 ratio
4,141765,NaN,16.0,26.0,0.85,NaN,79.0,NaN,NaN,NaN,NaN,3.7,NaN,142.0,NaN,NaN,NaN,NaN
6,143870,NaN,14.0,22.0,1.14,NaN,140.0,NaN,34.1,NaN,NaN,4.4,NaN,133.0,NaN,NaN,11.7,NaN
7,144815,3.6,6.0,26.0,0.63,NaN,82.0,NaN,36.6,NaN,NaN,3.7,NaN,141.0,NaN,0.5,7.9,NaN
12,145427,NaN,NaN,NaN,1.20,NaN,NaN,NaN,39.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.3,NaN
13,147306,NaN,NaN,NaN,0.65,NaN,NaN,NaN,36.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49957,3351763,NaN,23.0,27.0,0.66,NaN,117.0,NaN,NaN,NaN,NaN,4.7,NaN,134.0,NaN,NaN,NaN,NaN
50026,3352230,3.4,33.0,26.0,1.46,NaN,118.0,NaN,28.0,NaN,NaN,4.5,NaN,136.0,NaN,0.5,12.5,NaN
50034,3352231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50050,3352333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50053,3353113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.6,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#save to csv file
lab_pivot.to_csv("lab1.csv")